### PR TITLE
Use React error boundary

### LINKED ISSUE #613: Frontend: Add error boundary
https://reactjs.org/docs/error-boundaries.html
This should be a component that is shown when unhandled exception is thrown. Something like `Something went wrong, please try again or report on our github`.

### PR DESCRIPTION
**Pull request by petertrr**
* Add ErrorBoundary (https://reactjs.org/docs/error-boundaries.html)
* Add props for FallbackView

Closes #613 

image

### CODE REVIEW

**Comment by akuleshov7** [comment]
WOW!!!!

File: save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/ErrorBoundary.kt [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+            hasError = false
+        }
+    }
+
+    override fun render(): ReactNode? = if (state.hasError == true) {
+        div.create {
+            className = ClassName("container-fluid")
+            topBarComponent()
+            FallbackView::class.react {
+                bigText = "Error"
```
Comment (akuleshov7) [inline save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/ErrorBoundary.kt:47]: We do not pass an error number and error text here?

**Review by akuleshov7 — APPROVED** [review]

File: save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/ErrorBoundary.kt (hunk 1 above)
Comment (petertrr) [reply save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/ErrorBoundary.kt:47]: In this case the error is usually some sort of internal stack trace, so I just add a generic text
