### PR TITLE
ProjectView minor fixes 

### LINKED ISSUE #1215: `ProjectViewState.isConfirmWindowOpen` is unused
As of 3a3772598ae7e9759f04884f2b2509e4381ddfaf, this property is set in two places, but not used anymore. Corresponding modal window should either be restored or this logic should be cleared out.

### PR DESCRIPTION
**Pull request by sanyavertolet**
This PR closes #1215 

### What's done:
 - [x] Improved ProjectInfo by encapsulating update request in it
 - [x] Removed useless variables from `ProjectViewState`
 - [x] Moved deleteProject request down to `projectSettingsMenu`   
### Todo:
 * #1271

### CODE REVIEW

File: save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/FileUploader.kt [hunk 1]
```diff
@@ -95,11 +95,6 @@ external interface UploaderProps : PropsWithChildren {
      */
```
Comment (nulls) [inline save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/FileUploader.kt:95]: maybe make this FC more abstract and re-use for sandbox?

File: save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectSettingsMenu.kt [hunk 2]
```diff
@@ -82,18 +84,56 @@ private fun projectSettingsMenu() = FC<ProjectSettingsMenuProps> { props ->
...
+            loadingHandler = ::loadingHandler,
+        ).let {
+            if (it.ok) {
+                props.onProjectUpdate(draftProject)
+            }
+        }
+    }
+
+    val (isModalOpen, setIsModalOpen) = useState(false)
+    displayModal(
```
Comment (Cheshiriks) [inline save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectSettingsMenu.kt:122]: pls change on _displayConfirmationModal_

**Review by Cheshiriks — CHANGES_REQUESTED** [review]

File: save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectSettingsMenu.kt [hunk 3]
```diff
@@ -82,18 +84,56 @@ private fun projectSettingsMenu() = FC<ProjectSettingsMenuProps> { props ->
...
+            Json.encodeToString(draftProject.toDto()),
+            loadingHandler = ::loadingHandler,
+        ).let {
+            if (it.ok) {
+                props.onProjectUpdate(draftProject)
+            }
+        }
+    }
+
+    val (isModalOpen, setIsModalOpen) = useState(false)
```
Comment (nulls) [inline save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectSettingsMenu.kt:121]: suggestion to use `useWindowOpenness`

File: save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/FileUploader.kt (hunk 1 above)
Comment (sanyavertolet) [reply save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/FileUploader.kt:95]: Probably it is a good idea, but it is not that related to the fixes here. Will add a new issue for that.

File: save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectSettingsMenu.kt (hunk 3 above)
Comment (sanyavertolet) [reply save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectSettingsMenu.kt:121]: oh I do not like that hook :(

**Review by Cheshiriks — APPROVED** [review]

File: save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectSettingsMenu.kt (hunk 2 above)
Comment (nulls) [reply save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectSettingsMenu.kt:122]: > I would not like to use it as far as I want to use custom buttons here

maybe extend the `confirmation` button in `displayConfirmationModal` with default value `Yes`

**Review by petertrr — APPROVED** [review]

File: save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/FileUploader.kt (hunk 1 above)
Comment (sanyavertolet) [reply save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/FileUploader.kt:95]: Not yet, there is just a placeholder for it for now, but your suggestion is very nice, thx

File: save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectSettingsMenu.kt (hunk 3 above)
Comment (nulls) [reply save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectSettingsMenu.kt:121]: instead of general state with boolean value, it provides an object with methods with meaningful names like `isOpen`, `openWindow`/`closeWindow` and `openWindowAction`\`closeWindowAction`

Comment (sanyavertolet) [reply save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectSettingsMenu.kt:121]: It's more about ***over***loading imo🤓
But if you insist, I will do it

File: save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/ProjectInfo.kt [hunk 4]
```diff
@@ -98,15 +127,11 @@ fun projectInfo(
...
-                            } else {
-                                props.isEditDisabled ?: true
-                            }
+                            // temporary workaround for https://github.com/saveourtool/save-cloud/issues/589#issuecomment-1049674021
+                            disabled = fieldId != "name" && props.onProjectUpdate != null && isEditDisabled
+                            readOnly = fieldId == "name" || props.onProjectUpdate == null
                             onChange = { event ->
-                                val tg = event.target
-                                setDraftProject(idToValueSetter[fieldId]!!(tg.value))
+                                setDraftProject(idToValueSetter[fieldId]!!(event.target.value))
```
Comment (nulls) [inline save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/ProjectInfo.kt:134]: you can use `getValue` to avoid usage of `!!`

File: save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectSettingsMenu.kt (hunk 2 above)
Comment (sanyavertolet) [reply save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectSettingsMenu.kt:122]: Well, this is what we used to have. Let's better use `buttonBuilder`s and general `displayModal` instead of making simple methods more complicated.
Moreover, text is not the only thing that is needed to be changed. Style also should be changed.

File: save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/ProjectInfo.kt (hunk 4 above)
Comment (sanyavertolet) [reply save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/ProjectInfo.kt:134]: Thanks, will use it

File: save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectSettingsMenu.kt (hunk 3 above)
Comment (sanyavertolet) [reply save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectSettingsMenu.kt]: Done

File: save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/ProjectInfo.kt (hunk 4 above)
Comment (sanyavertolet) [reply save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/ProjectInfo.kt]: Done

**Review by nulls — APPROVED** [review]
