### PR TITLE
Minor fixes on frontend

### LINKED ISSUE #1057: `Create test project` button is unavailable before changing the organization
`Create test project` button is unavailable, even if all necessary fields are filled, until the organization will be changed.

Capture

### PR DESCRIPTION
**Pull request by sanyavertolet**
This PR closes #1057

### What's done:
 - [x] Fixed a bug with select form in `CreationView` - props were not set correctly so that the form didn't work fine
 - [x] Fixed a bug with `500` when `eligible-projects` endpoint is called - `eligible-projects` endpoint used to fetch all the projects (even deleted) as well as we used to allow Organization to be nullable implicitly - now only created projects are fetched by the endpoint  and organization is defiantly non-nullable
 - [x] Improved styles of `ContestEnroller`
 - [x] Added new style for react modals in order to provide better compatibility with bootstrap modals
 
### How it looks:
2022-08-18 в 12 51 47
2022-08-18 в 12 52 18

### CODE REVIEW

File: save-backend/src/main/kotlin/com/saveourtool/save/backend/service/LnkUserProjectService.kt [hunk 1]
```diff
@@ -117,7 +118,7 @@ class LnkUserProjectService(
      * @param userId
      * @return list of [Project]s that are connected to user with [userId]
      */
-    fun getAllProjectsByUserId(userId: Long): List<Project> = lnkUserProjectRepository.findByUserId(userId)
+    fun getCreatedProjectsByUserId(userId: Long): List<Project> = lnkUserProjectRepository.findByUserIdAndProjectStatus(userId, ProjectStatus.CREATED)
```
Comment (petertrr) [inline save-backend/src/main/kotlin/com/saveourtool/save/backend/service/LnkUserProjectService.kt:121]: Maybe `getExistingProjectsByUserId` or `getNonDeletedProjectsByUserId`? Because it kinda sounds like 'get projects created by this user'

File: save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/LnkContestProjectController.kt [hunk 2]
```diff
@@ -114,7 +114,7 @@ class LnkContestProjectController(
         @PathVariable contestName: String,
         authentication: Authentication,
     ): Mono<List<String>> = Mono.fromCallable {
-        lnkUserProjectService.getAllProjectsByUserId((authentication.details as AuthenticationDetails).id).filter { it.public }
```
Comment (kgevorkyan) [inline save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/LnkContestProjectController.kt:117]: As I remember, this request gives us the empty list, why `getCreatedProjectsByUserId` should help us, if the list of all projects are empty?

File: save-backend/src/main/kotlin/com/saveourtool/save/backend/service/LnkUserProjectService.kt (hunk 1 above)
Comment (sanyavertolet) [reply save-backend/src/main/kotlin/com/saveourtool/save/backend/service/LnkUserProjectService.kt:121]: Right, will fix it

**Comment by petertrr** [comment]
> Fixed a bug with select form in CreationView

@sanyavertolet please provide more details in the description on what exactly has been fixed

File: save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/LnkContestProjectController.kt (hunk 2 above)
Comment (sanyavertolet) [reply save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/LnkContestProjectController.kt:117]: The problem is that in prod database we have `DELETED` project with no organization while we somehow allow organization to be empty in `Project.kt` without setting organization type to be nullable

**Review by petertrr — APPROVED** [review]
