### PR TITLE
Fixed statistics display during uploading COSV files

### LINKED ISSUE #2798: Invalid statistics of raw cosv files
The field `availableFiles` contains only loaded raw cosv files on FE (pagination). Statistic should be calculated for all raw cosv files uploaded by current user

### PR DESCRIPTION
**Pull request by DrAlexD**
### What's done:
- added `GET` request to get statistics for raw cosv files.
- fixed statistics display.

Closes #2798

### CODE REVIEW

File: save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/cosv/RawCosvFileDto.kt [hunk 1]
```diff
@@ -33,4 +34,31 @@ data class RawCosvFileDto(
...
+    companion object {
+        /**
+         * @return [Boolean]
+         */
+        fun RawCosvFileDto.isArchive() = status == RawCosvFileStatus.UPLOADED && fileName.endsWith(ARCHIVE_EXTENSION, ignoreCase = true)
+
+        /**
+         * @return [Boolean]
+         */
+        fun RawCosvFileDto.isJsonFile() = status == RawCosvFileStatus.UPLOADED && !fileName.endsWith(ARCHIVE_EXTENSION, ignoreCase = true)
```
Comment (kgevorkyan) [inline save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/cosv/RawCosvFileDto.kt:47]: I thing !archive is not equals to the `json` file

Comment (nulls) [reply save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/cosv/RawCosvFileDto.kt:47]: also, no need to check status

Comment (DrAlexD) [reply save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/cosv/RawCosvFileDto.kt]: Changed to `isUploadedZipArchive()` and `isUploadedJsonFile()`. The idea is to store in statistics only count of recently uploaded archives and json files to display info about it. For other types of `status` for files, different statistical information is displayed.

File: save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/cosv/RawCosvFileDto.kt [hunk 2]
```diff
@@ -39,8 +39,36 @@ data class RawCosvFileDto(
...
+         * @return true if this raw cosv file is uploaded json file, checking by [fileName]
+         */
+        fun RawCosvFileDto.isUploadedJsonFile(): Boolean = status == RawCosvFileStatus.UPLOADED && !fileName.endsWith(ZIP_ARCHIVE_EXTENSION, ignoreCase = true)
+
+        /**
+         * Extracted as extension to avoid Jackson issue with encoding this field
+         *
+         * @return true if this raw cosv file is still processing, checking by [fileName]
+         */
+        fun RawCosvFileDto.isProcessing(): Boolean = status == RawCosvFileStatus.PROCESSED || status == RawCosvFileStatus.IN_PROGRESS
```
Comment (nulls) [inline save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/cosv/RawCosvFileDto.kt:58]: why `PROCESSED` is `isProcessing`?

File: save-cosv/src/main/kotlin/com/saveourtool/save/cosv/storage/RawCosvFileStorage.kt [hunk 3]
```diff
@@ -63,13 +68,22 @@ class RawCosvFileStorage(
...
         userName: String,
-    ): Mono<Long> = blockingToMono {
-        s3KeyManager.countByOrganizationAndUser(organizationName, userName)
+    ): Mono<RawCosvFileStatisticsDto> = blockingToMono {
+        val filesList = s3KeyManager.listByOrganizationAndUser(organizationName, userName).toList()
+        RawCosvFileStatisticsDto(
+            s3KeyManager.countByOrganizationAndUser(organizationName, userName),
+            filesList.count { it.isUploadedZipArchive() }.toLong(),
+            filesList.count { it.isUploadedJsonFile() }.toLong(),
+            s3KeyManager.countByOrganizationAndUserAndStatus(organizationName, userName, RawCosvFileStatus.PROCESSED) +
```
Comment (nulls) [inline save-cosv/src/main/kotlin/com/saveourtool/save/cosv/storage/RawCosvFileStorage.kt:82]: you already fetched all `filesList` -- maybe use them instead of additional calls to database

File: save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/fileuploader/CosvFileManagerComponent.kt [hunk 4]
```diff
@@ -54,13 +58,13 @@ val cosvFileManagerComponent: FC<Props> = FC {
     @Suppress("GENERIC_VARIABLE_WRONG_DECLARATION")
     val organizationSelectForm = selectFormRequired<String>()
 
-    val (allAvailableFilesCount, setAllAvailableFilesCount) = useState(0L)
+    val (statistic, setStatistic) = useState<RawCosvFileStatisticsDto>()
```
Comment (nulls) [inline save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/fileuploader/CosvFileManagerComponent.kt:61]: suggestion to create `RawCosvFileStatisticsDto.empty = RawCosvFileStatisticsDto(0, 0, 0, 0, ...)` and use it instead of checking on null

Comment (DrAlexD) [reply save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/fileuploader/CosvFileManagerComponent.kt]: Done

File: save-cosv/src/main/kotlin/com/saveourtool/save/cosv/storage/RawCosvFileStorage.kt (hunk 3 above)
Comment (DrAlexD) [reply save-cosv/src/main/kotlin/com/saveourtool/save/cosv/storage/RawCosvFileStorage.kt]: Done

File: save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/cosv/RawCosvFileStatisticsDto.kt [hunk 5]
```diff
@@ -0,0 +1,34 @@
...
+data class RawCosvFileStatisticsDto(
+    val allAvailableFilesCount: Int,
+    val uploadedArchivesCount: Int,
+    val uploadedJsonFilesCount: Int,
+    val processingFilesCount: Int,
+    val duplicateFilesCount: Int,
+    val errorFilesCount: Int,
+) {
+    companion object {
+        val empty = RawCosvFileStatisticsDto(
```
Comment (nulls) [inline save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/cosv/RawCosvFileStatisticsDto.kt:25]: diktat requires KDoc here, doesn't it?

**Review by kgevorkyan — APPROVED** [review]

**Review by Cheshiriks — APPROVED** [review]
