### PR TITLE
Fixed database issues in sandbox

### LINKED ISSUE #1241: [Sandbox] Add AgentRepository in `orchestrator`
Need to introduce `AgentRepository` for `sandbox` mode in `orchestrator`.
It should use a new database, also need to add endpoints to check content there

### PR DESCRIPTION
**Pull request by nulls**
Closes #1241

### CODE REVIEW

File: save-sandbox/src/main/kotlin/com/saveourtool/save/sandbox/entity/SandboxAgentStatus.kt [hunk 1]
```diff
@@ -28,7 +28,7 @@ class SandboxAgentStatus(
     @Enumerated(EnumType.STRING)
     var state: AgentState,
 
-    @ManyToOne(fetch = FetchType.LAZY)
+    @ManyToOne(fetch = FetchType.EAGER)
```
Comment (akuleshov7) [inline save-sandbox/src/main/kotlin/com/saveourtool/save/sandbox/entity/SandboxAgentStatus.kt:31]: why eager here? I thought that LAZY will also ok here

**Review by akuleshov7 — APPROVED** [review]

File: save-sandbox/src/main/kotlin/com/saveourtool/save/sandbox/entity/SandboxAgentStatus.kt (hunk 1 above)
Comment (nulls) [reply save-sandbox/src/main/kotlin/com/saveourtool/save/sandbox/entity/SandboxAgentStatus.kt:31]: We already got similar problem: there is an issue with hibernate proxy object, which loaded lazy. Eager is the simpler solution
