### PR TITLE
Loading handler fix for fileUploader

### LINKED ISSUE #826: LoadingHandler follow-ups
* Organization settings view hangs on loading after page refresh
* Loading animation is not displayed when number of entries in a table is changed (e.g. `show 10 entries` -> `show 100 entries`: there seems to be a loading period, but no animation is displayed)

### PR DESCRIPTION
**Pull request by sanyavertolet**
This PR closes #826 

### What's done:
- [x] Disabled loadingHandler for file uploading

### CODE REVIEW

**Review by petertrr — APPROVED** [review]

File: save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ProjectView.kt [hunk 1]
```diff
@@ -753,7 +753,7 @@ class ProjectView : AbstractView<ProjectExecutionRouteProps, ProjectViewState>(f
                         FormData().apply {
                             append("file", file)
                         },
-                        loadingHandler = ::classLoadingHandler,
```
Comment (akuleshov7) [inline save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ProjectView.kt:756]: How this affected us?
