### PR TITLE
Fixed text displaying in tables on user and organization pages

### LINKED ISSUE #2643: Tables: check project and organization and remove ugly tables (replace them with our good-looking tables). Start from vulnerabilities - unify it's logic

### PR DESCRIPTION
**Pull request by DrAlexD**
### What's done:
- vulnerabilities and users tabs are now only displayed if there are new users to approve.
- added text centering in tables on user, organization and project pages.
- added colors for `Status` field depending on its value in the vulnerability table.
- added colors for `Criticality` field depending on its value in the vulnerability table.

image

Closes #2643

### CODE REVIEW

File: save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/OrganizationContestsMenu.kt [hunk 1]
```diff
@@ -89,8 +94,6 @@ private val contestsTable: FC<OrganizationContestsTableProps<ContestDto>> = tabl
             }
         }
     },
-    initialPageSize = 10,
```
Comment (kgevorkyan) [inline save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/OrganizationContestsMenu.kt:92]: ?

**Review by kgevorkyan — APPROVED** [review]

File: save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/OrganizationContestsMenu.kt (hunk 1 above)
Comment (DrAlexD) [reply save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/OrganizationContestsMenu.kt:92]: There is no need to pass `initialPageSize = 10` because the default value for this property is 10 and is contained in the `INITIAL_TABLE_PAGE_SIZE` constant.

**Review by Cheshiriks — APPROVED** [review]

**Review by nulls — APPROVED** [review]
