### PR TITLE
Bug on ContestView with invalid URL

### LINKED ISSUE #1165: Bug on ContestView with invalid  URL
When entering an invalid contest name in the url, we stay on the original page instead of going to 404
Contest

### PR DESCRIPTION
**Pull request by Cheshiriks**
* fixed bug on ContestView 
Closes #1165

### CODE REVIEW

File: save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ContestView.kt [hunk 1]
```diff
@@ -88,20 +96,35 @@ class ContestView : AbstractView<ContestViewProps, ContestViewState>(false) {
...
     }
 
     override fun componentDidMount() {
         super.componentDidMount()
         urlAnalysis(ContestMenuBar, Role.NONE, false)
         getIsFeaturedAndSetState()
+        getContest()
+    }
+
+    private fun getContest() {
```
Comment (nulls) [inline save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ContestView.kt:111]: suggestion to rename `getContest` to `fetchContest` for example, because it's not a getter

Comment (Cheshiriks) [reply save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ContestView.kt]: Renamed

File: save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ContestView.kt [hunk 2]
```diff
@@ -69,6 +71,11 @@ external interface ContestViewState : State, HasSelectedMenu<ContestMenuBar> {
      * Flag that shows if current contest is featured or not
      */
     var isFeatured: Boolean
+
+    /**
+     * Contest
```
Comment (petertrr) [inline save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ContestView.kt:76]: Please indicate with a comment somewhere that this field is unused but acts as a marker of contest existence

**Review by petertrr — APPROVED** [review]

File: save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ContestView.kt (hunk 2 above)
Comment (Cheshiriks) [reply save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ContestView.kt:76]: This field is now used to get the name of the contest in the view header

**+state.contest.name**
