### PR TITLE
Fixed long usernames don't fit into their placeholders.

### LINKED ISSUE #1195: [save-frontend] long usernames don't fit into their placeholders
UX may vary depending on the screen resolution, but on a 1920x1080 screen, the maximum user name length to fit into the UI seems to be like 20 characters:

save-long-user-name

The same screenshot with devtools panel open:

save-long-user-name-devtools

### PR DESCRIPTION
**Pull request by DrAlexD**
### What's done:
- `isLengthOk` function has been changed so that in boundary cases number of characters matches maximum allowed length.
- added `shortenLoginWithTooltipIfNecessary` and `shortenRealNameWithTooltipIfNecessary` functions for names validation into their placeholders, which are in UserProfileView and SettingsView.
- added `shorten` function to shorten any string.
- added `shortenLogin` and `shortenRealName` functions to shorten strings of login and real name.

Closes #1195

image
image
image

### CODE REVIEW

**Comment by Cheshiriks** [comment]
Please add screenshots if you change any visual display on the front end.

File: save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/userprofile/UserProfileView.kt [hunk 1]
```diff
@@ -371,6 +373,42 @@ fun ChildrenBuilder.renderLeftUserMenu(
...
+ * @param header
+ */
+fun ChildrenBuilder.validateName(name: String?, header: HTMLAttributes<HTMLHeadingElement>) {
+    name?.let {
+        if (it.length > 14) {
+            asDynamic()["data-toggle"] = "tooltip"
+            asDynamic()["data-placement"] = "bottom"
+            header.title = it
+
+            +(it.substring(0, 13) + "...")
```
Comment (nulls) [inline save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/userprofile/UserProfileView.kt:387]: there is a file `save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/StringUtils.kt`
can you please add this method there?

File: save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/userprofile/UserProfileView.kt [hunk 2]
```diff
@@ -371,6 +373,42 @@
...
+        }
+    } ?: "N/A"
+}
+
+/**
+ * @param realName
+ * @param header
+ */
+fun ChildrenBuilder.validateRealName(realName: String?, header: HTMLAttributes<HTMLHeadingElement>) {
+    realName?.let {
```
[the remark this answers is not in the document]
Comment (nulls) [reply save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/userprofile/UserProfileView.kt:399]: you can use `realName` instead of `it` in `let` -- kotlin should understand that it's not nullable

File: save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/userprofile/UserProfileView.kt [hunk 3]
```diff
@@ -371,6 +373,42 @@ fun ChildrenBuilder.renderLeftUserMenu(
     }
 }
 
+/**
+ * @param name
+ * @param header
+ */
+fun ChildrenBuilder.validateName(name: String?, header: HTMLAttributes<HTMLHeadingElement>) {
```
Comment (kgevorkyan) [inline save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/userprofile/UserProfileView.kt:380]: may be rename to smth like `shortenTheNameIfNecessary`

File: save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/userprofile/UserProfileView.kt (hunk 2 above)
[the remark this answers is not in the document]
Comment (DrAlexD) [reply save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/userprofile/UserProfileView.kt]: Done

File: save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/userprofile/UserProfileView.kt (hunk 1 above)
Comment (DrAlexD) [reply save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/userprofile/UserProfileView.kt]: Done

File: save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/userprofile/UserProfileView.kt (hunk 3 above)
Comment (DrAlexD) [reply save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/userprofile/UserProfileView.kt]: Done

File: save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/StringUtils.kt [hunk 4]
```diff
@@ -12,3 +15,13 @@ fun List<String>?.listToShortString(): String = this?.run {
         "${first()} ... ${last()}"
     }
 }.orEmpty()
+
+/**
+ * @return short [String] for login
+ */
+fun String?.shortenLogin(): String = this?.substring(0, LOGIN_MAX_LENGTH - 1) + "..."
```
Comment (nulls) [inline save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/StringUtils.kt:22]:
```suggestion
fun String.shorten(maxLength): String = substring(0, maxLength - 1) + "..." 

/**
 * @return short [String] for login
 */
fun String.shortenLogin(): String = shorten(LOGIN_MAX_LENGTH)

/**
 * @return short [String] for real name
 */
fun String.shortenRealName(): String = shorten(REAL_NAME_PART_MAX_LENGTH)
```

File: save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/StringUtils.kt [hunk 5]
```diff
@@ -12,3 +15,13 @@ fun List<String>?.listToShortString(): String = this?.run {
...
+
+/**
+ * @return short [String] for real name
+ */
+fun String?.shortenRealName(): String = this?.substring(0, REAL_NAME_PART_MAX_LENGTH - 1) + "..."
```
Comment (nulls) [inline save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/StringUtils.kt:27]: why do we generate `...` for null?

File: save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/StringUtils.kt (hunk 4 above)
Comment (DrAlexD) [reply save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/StringUtils.kt]: Done

File: save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/StringUtils.kt (hunk 5 above)
Comment (DrAlexD) [reply save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/StringUtils.kt]: Done

**Review by nulls — APPROVED** [review]

**Review by nulls — APPROVED** [review]

**Review by Cheshiriks — APPROVED** [review]
