### PR TITLE
[DEMO] GithubDownloadToolService

### LINKED ISSUE #1491: [DEMO] Don't rely on `curl` for downloads in `save-demo`
`curl` is not available in `save-demo` image and `diktat-cli` fails

cc @sanyavertolet

### PR DESCRIPTION
**Pull request by sanyavertolet**
This PR closes #1491

### What's done:
 * Added `GithubDownloadToolService` that downloads files (`ktlint` and `diktat-1.2.3.jar`) to storage
 * Reworked `ToolStorage` structure

### Todo:
 * Add database support in order to store information about versions that should be downloaded to storage

### CODE REVIEW

File: save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/diktat/DiktatDemoTool.kt [hunk 1]
```diff
@@ -2,16 +2,19 @@ package com.saveourtool.save.demo.diktat
...
+ * @property toolName
+ * @property version
  */
-enum class DiktatDemoTool {
+enum class DiktatDemoTool(val owner: String, val toolName: String, val version: String) {
     /**
      * Run diktat
      */
-    DIKTAT,
+    DIKTAT("saveourtool", "diktat", "v1.2.3"),
```
Comment (kgevorkyan) [inline save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/diktat/DiktatDemoTool.kt:13]: Could we move versions in some common place? You use it in 3 places

Comment (sanyavertolet) [reply save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/diktat/DiktatDemoTool.kt:13]: It is planned to use database for that (create a new scheme like it is done in `save-sandbox`)

File: save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/diktat/DiktatDemoTool.kt [hunk 2]
```diff
@@ -2,16 +2,19 @@ package com.saveourtool.save.demo.diktat
 
 /**
  * Enum that represents possible tool names in diktat-demo
+ * @property owner
+ * @property toolName
+ * @property version
  */
-enum class DiktatDemoTool {
+enum class DiktatDemoTool(val owner: String, val toolName: String, val version: String) {
```
Comment (0x6675636b796f75676974687562) [inline save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/diktat/DiktatDemoTool.kt:9]: This is not actually a version &mdash; this is essentially a Git tag (which, generally, is different from the release name.

Could you please rename it accordingly?

```suggestion
enum class DiktatDemoTool(val owner: String, val toolName: String, val vcsTagName: String) {
```

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/Runner.kt [hunk 3]
```diff
@@ -7,7 +7,7 @@ import java.nio.file.Path
 /**
  * Interface should be implemented by all the runners.
  */
-interface Runner<in P : DemoAdditionalParams, out R : DemoResult> {
+interface Runner<in P : DemoAdditionalParams, in K, out R : DemoResult> {
```
Comment (0x6675636b796f75676974687562) [inline save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/Runner.kt:10]: Is `K` nullable? 

If not, probably `K : Any` then?

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/cli/DiktatCliRunner.kt [hunk 4]
```diff
@@ -32,57 +32,41 @@ import kotlin.io.path.*
...
+    ): String = buildString {
+        // TODO: this information should not be hardcoded but stored in database
+        val ktlintExecutable = getExecutable(workingDir, DiktatDemoTool.KTLINT.toToolKey("ktlint"))
+        val diktatExecutable = getExecutable(workingDir, DiktatDemoTool.DIKTAT.toToolKey("diktat-1.2.3.jar"))
+        append(ktlintExecutable)
+        append(" -R $diktatExecutable ")
+        append(" --disabled_rules=standard")
+        append(" --reporter=plain,output=$outputPath ")
+        configPath?.let {
+            append(" --config=$it ")
```
Comment (petertrr) [inline save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/cli/DiktatCliRunner.kt:51]: Is it supposed to be diktat config? Diktat doesn't accept config from an argument, because ktlint doesn't give access to the arguments. You can use a JVM property or rely on a specific location of a file

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/cli/CliRunner.kt [hunk 5]
```diff
@@ -12,7 +12,7 @@ import kotlin.io.path.*
  * Interface that should be implemented by all the runners that use [ProcessBuilder] in order to run tools for demo.
  */
 @Component
-interface CliRunner <in P : DemoAdditionalParams, out R : DemoResult> : Runner<P, R> {
+interface CliRunner <in P : DemoAdditionalParams, in K, out R : DemoResult> : Runner<P, K, R> {
```
Comment (0x6675636b796f75676974687562) [inline save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/cli/CliRunner.kt:15]: Is `K` nullable?

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/cli/DiktatCliRunner.kt [hunk 6]
```diff
@@ -32,57 +32,41 @@ import kotlin.io.path.*
...
+    private fun getRunCommandForDiktat(
+        workingDir: Path,
+        testPath: Path,
+        outputPath: Path,
+        configPath: Path?,
+        params: DiktatDemoAdditionalParams,
+    ): String = buildString {
+        // TODO: this information should not be hardcoded but stored in database
+        val ktlintExecutable = getExecutable(workingDir, DiktatDemoTool.KTLINT.toToolKey("ktlint"))
+        val diktatExecutable = getExecutable(workingDir, DiktatDemoTool.DIKTAT.toToolKey("diktat-1.2.3.jar"))
```
Comment (0x6675636b796f75676974687562) [inline save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/cli/DiktatCliRunner.kt:45]: And here, `1.2.3` is the **version** (as opposed to the VCS tag), so please extract it and store alongside the **tag**.

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt [hunk 7]
```diff
@@ -0,0 +1,109 @@
+package com.saveourtool.save.demo.service
+
+import com.saveourtool.save.demo.entities.ReleaseAsset
+import com.saveourtool.save.demo.entities.ReleaseMetadata
+import com.saveourtool.save.demo.storage.ToolKey
+import com.saveourtool.save.demo.storage.ToolStorage
+import com.saveourtool.save.demo.utils.toByteBufferFlux
+
+import io.ktor.client.*
```
Comment (petertrr) [inline save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt:9]: Any particular reason to use ktor here?

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/HttpUtils.kt [hunk 8]
```diff
@@ -0,0 +1,21 @@
...
+import io.ktor.utils.io.jvm.javaio.*
+import org.springframework.core.io.buffer.DataBufferUtils
+import org.springframework.core.io.buffer.DefaultDataBufferFactory
+import reactor.core.publisher.Flux
+import java.nio.ByteBuffer
+
+private const val DEFAULT_BUFFER_SIZE = 4096
+
+/**
+ * @return [Flux] of [ByteBuffer]s read from [ByteReadChannel]
```
Comment (0x6675636b796f75676974687562) [inline save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/HttpUtils.kt:15]: What happens if

 - the read channel is empty?
 - an `IOException` is thrown when reading from the channel?
 
 Please document this behaviour.

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/cli/DiktatCliRunner.kt (hunk 6 above)
Comment (sanyavertolet) [reply save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/cli/DiktatCliRunner.kt:45]: The point is that executable name is fetched from GitHub so we do not need to hardcode it, either database should be used to store this kind of information, or storage itself (e.g. list or something like that). Database is needed in order to keep all the data to construct the URL for download as well as dependencies (like it is in `diktat` - it requires a special version of `ktlint`)

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/Runner.kt [hunk 9]
```diff
@@ -7,7 +7,7 @@ import java.nio.file.Path
 /**
  * Interface should be implemented by all the runners.
```
[the remark this answers is not in the document]
Comment (sanyavertolet) [reply save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/Runner.kt:8]: Sure, will do it

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/Runner.kt (hunk 3 above)
Comment (sanyavertolet) [reply save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/Runner.kt:10]: It is not, will do as you suggested

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt [hunk 10]
```diff
@@ -0,0 +1,109 @@
...
+
+    @PostConstruct
+    private fun loadToStorage() = toolStorage.list()
+        .collectList()
+        .flatMapIterable { availableFiles ->
+            supportedTools.filter {
+                it !in availableFiles
+            }
+        }
+        .flatMap { key ->
```
Comment (petertrr) [inline save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt:90]: Logging may be useful here

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/HttpUtils.kt (hunk 8 above)
Comment (sanyavertolet) [reply save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/HttpUtils.kt:15]: Oh ok

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/cli/DiktatCliRunner.kt (hunk 4 above)
Comment (sanyavertolet) [reply save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/cli/DiktatCliRunner.kt:51]: Ok, thanks, will fix it

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt (hunk 7 above)
Comment (sanyavertolet) [reply save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt:9]: HttpClient is required here.
Do you suggest using `Spring`'s one?

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt (hunk 10 above)
Comment (sanyavertolet) [reply save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt:90]: Will add it

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/storage/ToolStorage.kt [hunk 11]
```diff
@@ -20,34 +16,13 @@ private const val TOOLS_PATH = "tools"
...
-            }
-            .flatMap { key ->
-                upload(key, ClassPathResource(key.executableName).toByteBufferFlux()).thenReturn(key)
-            }
-            .subscribe()
-    }
-
+    @Suppress("COMPLEX_EXPRESSION")
     override fun buildKey(rootDir: Path, pathToContent: Path): ToolKey = ToolKey(
+        pathToContent.parent.parent.parent.name,
```
Comment (0x6675636b796f75676974687562) [inline save-demo/src/main/kotlin/com/saveourtool/save/demo/storage/ToolStorage.kt:21]: Please extract `pathToContent.parent` and `pathToContent.parent.parent` into local variables.

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt [hunk 12]
```diff
@@ -0,0 +1,109 @@
...
+            downloadFromGithubAndUploadToStorage(key).toMono()
+        }
+        .subscribe()
+
+    companion object {
+        private const val GITHUB_API_URL = "https://api.github.com/repos"
+        private const val LATEST_VERSION = "latest"
+        private val supportedTools = listOf(
+            ToolKey("pinterest", "ktlint", "0.46.1", "ktlint"),
+            ToolKey("saveourtool", "diktat", "v1.2.3", "diktat-1.2.3.jar"),
```
Comment (0x6675636b796f75676974687562) [inline save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt:100]: Git tag and version to be extracted.

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/service/AbstractDemoService.kt [hunk 13]
```diff
@@ -7,8 +7,8 @@ import com.saveourtool.save.demo.runners.cli.CliRunner
 /**
  * Abstract service interface for different demonstration services
  */
-abstract class AbstractDemoService<in P : DemoAdditionalParams, out R : DemoResult>(
-    private val runner: CliRunner<P, R>,
+abstract class AbstractDemoService<in P : DemoAdditionalParams, in K, out R : DemoResult>(
```
Comment (0x6675636b796f75676974687562) [inline save-demo/src/main/kotlin/com/saveourtool/save/demo/service/AbstractDemoService.kt:10]: Please document the type parameter.

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/cli/DiktatCliRunner.kt [hunk 14]
```diff
@@ -32,57 +32,41 @@ import kotlin.io.path.*
...
-            .block()
-            .let { requireNotNull(it) }
-            .apply {
-                toFile().setExecutable(true, false)
-            }
+        append(testPath)
     }
 
-    override fun getRunCommand(
+    private fun getRunCommandForKtlint(
```
Comment (0x6675636b796f75676974687562) [inline save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/cli/DiktatCliRunner.kt:59]: Diktat command line is actually a ktlint command line with three extra parameters:

 - `-R`
 - `diktat.jar`
 - `--disabled_rules=standard`
 
 Please refactor so that common code is shared.

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/cli/DiktatCliRunner.kt (hunk 6 above)
Comment (0x6675636b796f75676974687562) [reply save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/cli/DiktatCliRunner.kt:45]: Fair enough.

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/HttpUtils.kt (hunk 8 above)
Comment (sanyavertolet) [reply save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/HttpUtils.kt:15]: For now I am not that sure about the behavior you asked to consider. Opened #1528 in order to add unit tests for this logic.

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/storage/ToolStorage.kt (hunk 11 above)
Comment (sanyavertolet) [reply save-demo/src/main/kotlin/com/saveourtool/save/demo/storage/ToolStorage.kt:21]: To my mind there are two possible solutions:
1. Leave as is as far as it is a kind of logic that is very internal (probably add tests for it)
2. Move ALL the `pathToContent.**.name` to separate local variables with nice names

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/Runner.kt (hunk 3 above)
Comment (sanyavertolet) [reply save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/Runner.kt]: Done

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/Runner.kt (hunk 9 above)
[the remark this answers is not in the document]
Comment (sanyavertolet) [reply save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/Runner.kt:8]: Done

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/cli/CliRunner.kt (hunk 5 above)
Comment (sanyavertolet) [reply save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/cli/CliRunner.kt]: Done

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/cli/DiktatCliRunner.kt (hunk 4 above)
Comment (sanyavertolet) [reply save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/cli/DiktatCliRunner.kt]: Removed it as config file is saved in working dir. Let's try to rely on a specific location (and maybe cover it with tests)

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt (hunk 10 above)
Comment (sanyavertolet) [reply save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt:111]: Provided logging for `GithubDownloadToolService`

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt [hunk 15]
```diff
@@ -0,0 +1,109 @@
...
+        .flatMap { key ->
+            downloadFromGithubAndUploadToStorage(key).toMono()
+        }
+        .subscribe()
+
+    companion object {
+        private const val GITHUB_API_URL = "https://api.github.com/repos"
+        private const val LATEST_VERSION = "latest"
+        private val supportedTools = listOf(
+            ToolKey("pinterest", "ktlint", "0.46.1", "ktlint"),
```
[the remark this answers is not in the document]
Comment (sanyavertolet) [reply save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt]: Slightly reworked it (not values from enum are used, later will be moved to database)

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/service/AbstractDemoService.kt (hunk 13 above)
Comment (sanyavertolet) [reply save-demo/src/main/kotlin/com/saveourtool/save/demo/service/AbstractDemoService.kt]: Done

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt (hunk 12 above)
Comment (sanyavertolet) [reply save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt]: Discussed above, I guess

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/cli/DiktatCliRunner.kt (hunk 14 above)
Comment (sanyavertolet) [reply save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/cli/DiktatCliRunner.kt]: Done, combined two methods into one with `if (tool == DIKTAT)`

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt (hunk 7 above)
Comment (petertrr) [reply save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt:12]: I mean, now that everything is done already, it's not worth changing. But yes, I was asking if there was a particular preference towards `ktor-client` over Spring's `WebClient`

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt [hunk 16]
```diff
@@ -0,0 +1,132 @@
...
+        }
+        .flatMap { key ->
+            downloadFromGithubAndUploadToStorage(key).toMono()
+        }
+        .subscribe()
+
+    companion object {
+        @Suppress("GENERIC_VARIABLE_WRONG_DECLARATION")
+        private val logger = getLogger<GithubDownloadToolService>()
+        private const val GITHUB_API_URL = "https://api.github.com/repos"
```
Comment (nulls) [inline save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt:119]: why github? maybe download artifact from maven central?

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/storage/ToolStorage.kt (hunk 11 above)
Comment (nulls) [reply save-demo/src/main/kotlin/com/saveourtool/save/demo/storage/ToolStorage.kt:21]: there is a method: `com.saveourtool.save.utils.FileUtilsKt#pathNamesTill`
```suggestion
val (rootDir, ownerName, toolName, vcsTagName, executableName) = pathToContent.pathNamesTill(rootDir)
return ToolKey(rootDir, ownerName, toolName, vcsTagName, executableName)
```

Comment (sanyavertolet) [reply save-demo/src/main/kotlin/com/saveourtool/save/demo/storage/ToolStorage.kt:21]: Oh wow, that might be super useful here, thanks

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt (hunk 16 above)
Comment (sanyavertolet) [reply save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt:119]: AFAIU, maven central is mostly used by java developers while GitHub is popular among the majority of developers

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/storage/ToolStorage.kt (hunk 11 above)
Comment (sanyavertolet) [reply save-demo/src/main/kotlin/com/saveourtool/save/demo/storage/ToolStorage.kt]: BTW, @nulls, this method needs kdoc as far as it is not obvious that `rootDir` is also returned. will do it

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt (hunk 16 above)
Comment (0x6675636b796f75676974687562) [reply save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt:119]: > why github? maybe download artifact from maven central?

Because neither we nor _KtLint_ maintainers publish executable _fat jars_ to _Maven Central_.

This is about downloading release assets in terms of GitHub, not about transitive dependencies in Gradle/Maven/IOvy sense.

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt (hunk 7 above)
Comment (0x6675636b796f75676974687562) [reply save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt:12]: The reason was that some code was borrowed from `:save-api` (the REST client), which originally depended on _Ktor_, not _Spring_. For the same reason, `saveourtool/save-backend-tests` depend on _Ktor_.

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt (hunk 16 above)
Comment (nulls) [reply save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt:119]: > AFAIU, maven central is mostly used by java developers while GitHub is popular among the majority of developers regardless the language

agree, good point

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt (hunk 7 above)
Comment (nulls) [reply save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt:12]: > I mean, now that everything is done already, it's not worth changing. But yes, I was asking if there was a particular preference towards `ktor-client` over Spring's `WebClient`

actually, if we will leave `ktor`, it will allow to use this Service as separate tool (without Spring's ecosystem) to download artifacts from github.

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/HttpUtils.kt [hunk 17]
```diff
@@ -0,0 +1,24 @@
+@file:Suppress("HEADER_MISSING_IN_NON_SINGLE_CLASS_FILE")
```
Comment (0x6675636b796f75676974687562) [inline save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/HttpUtils.kt:1]: How we have three (yes, **three**, Carl!) files named `HttpUtils.kt` in our codebase.

Maybe it's time to finally merge their content?

**Review by 0x6675636b796f75676974687562 — APPROVED** [review]
LGTM

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt (hunk 16 above)
Comment (0x6675636b796f75676974687562) [reply save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt:119]: > ktlint uploads https://repo1.maven.org/maven2/com/pinterest/ktlint/0.47.1/ktlint-0.47.1-all.jar to maven central.

Thanks, was unaware of that.

So, they're using the `all` qualifier.
Probably we should do the same with _Diktat_ fat JAR, too.

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/HttpUtils.kt (hunk 8 above)
Comment (sanyavertolet) [reply save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/HttpUtils.kt:18]: @0x6675636b796f75676974687562 thanks for your commitment

File: save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/HttpUtils.kt (hunk 17 above)
Comment (sanyavertolet) [reply save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/HttpUtils.kt:1]: It seems that one of this files is located in `Kotlin Native` section while another one from `jvm` section (save-api) does not depend on `reactor`. In my third `HttpUtils.kt` file I need both `reactor` and `ktor` dependencies (as well as `spring` lol)
