### PR TITLE
TestSuiteSelector search mode fix

### LINKED ISSUE #1834: Search in the selector view does not work
image

### PR DESCRIPTION
**Pull request by sanyavertolet**
This PR closes #1834

### What's done:
 * Fixed `/filtered` endpoint - @nulls has broken it by adding new field to `TestSuite` forgetting about `ExampleMatcher`'s `ignorePaths`

### CODE REVIEW

File: save-backend/src/main/kotlin/com/saveourtool/save/backend/service/TestSuitesService.kt [hunk 1]
```diff
@@ -91,7 +91,7 @@ class TestSuitesService(
                 .withMatcher("name", ExampleMatcher.GenericPropertyMatchers.contains().ignoreCase())
                 .withMatcher("language", ExampleMatcher.GenericPropertyMatchers.contains().ignoreCase())
                 .withMatcher("tags", ExampleMatcher.GenericPropertyMatchers.contains().ignoreCase())
-                .withIgnorePaths("description", "source", "version", "dateAdded", "plugins")
+                .withIgnorePaths("description", "source", "version", "dateAdded", "plugins", "sourceSnapshot")
```
Comment (nulls) [inline save-backend/src/main/kotlin/com/saveourtool/save/backend/service/TestSuitesService.kt:94]: `source` can be removed and please add a link/note about this runtime dependency to entity class

**Review by nulls — CHANGES_REQUESTED** [review]

File: save-backend/src/main/kotlin/com/saveourtool/save/backend/service/TestSuitesService.kt (hunk 1 above)
Comment (sanyavertolet) [reply save-backend/src/main/kotlin/com/saveourtool/save/backend/service/TestSuitesService.kt]: Replaced `source` with `sourceSnapshot` as well as added reminder to `TestSuite`'s KDoc

**Review by nulls — APPROVED** [review]
